### PR TITLE
add make example

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
I heard you like make 😄

**Review by lgersman — APPROVED** [review]

**Comment by wader** [comment]
👍  i didn't understand how to generate the main README.md so i skipped that

**Comment by lgersman** [comment]
> I heard you like make smile

yes yes yes - with all the do's and dont's

**Comment by lgersman** [comment]
> +1 i didn't understand how to generate the main README.md so i skipped that

just run `./build.sh` in the project root. it will regenerate all README.md files.

... i just asked myself why the hell i didnt wrote a Makefile for this job 😅

**Comment by wader** [comment]
Ah doh! somehow missed that there was a README.md.template there :) just looked at the build.sh script and scrached my head

**Comment by lgersman** [comment]
Thanks for your contribution 🙏.

**Comment by wader** [comment]
Thanks spreading knowledge about make, i'm an avid user :) not sure i will use SHELL but interesting to know about it. BTW Dockerfile:s has a similar SHELL functionality 🤔😬

**Comment by lgersman** [comment]
Yes, you're absolutely right - I always use 

- `SHELL ["/bin/bash", "-o", "pipefail", "-c"]` in Dockerfile's to ensure bash is used (like here https://github.com/lgersman/pnpmkambrium/blob/55752f1cb4b7d1c84dc5ec5b241375fa9c8cd7f9/packages/docker/shaunch/Dockerfile#L6)

- `SHELL != sh -c "command -v bash"` and `.SHELLFLAGS := -eu -o pipefail -c` in Makefile's to ensure bash is used for the recipe body execution

You can't stress enough how important this is 😅

**Comment by wader** [comment]
Oh good point doing the same with make 👍

Was thinking if it would be possible to make the RUN argument in a Dockerfile be a Makefile 😄

**Pull request merged**
